[project]
name = "csca5622-final-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jupyterlab>=4.4.9",
    "scikit-learn>=1.7.2",
]
